codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%

ignore:
  - "tests/**/*"
  - "_deps/**/*"
  - "samples/**/*"
  - "build/_deps/**/*"
